# General
shell zsh
font_size 11.3
window_padding_width 5
scrollback_lines 10000
scrollback_pager_history_size 20
clipboard_control write-clipboard write-primary read-clipboard read-primary
paste_actions no-op
confirm_os_window_close 0
pixel_scroll yes	

# tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_bar_min_tabs 1

# Theming
include current-theme.conf
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
shell_integration no-cursor
background_opacity 1
hide_window_decorations no
cursor_shape beam
cursor_trail 1
cursor_trail_decay 0.1 0.15

# layout
enabled_layouts splits,tall:bias=62;full_size=0;mirrored=false
draw_minimal_borders yes
window_border_width 0.2pt

# mappings
map ctrl+shift+enter launch --location=hsplit --cwd=current
map ctrl+shift+\ launch --location=vsplit --cwd=current
map alt+shift+h neighboring_window left
map alt+shift+l neighboring_window right
map alt+shift+k neighboring_window up
map alt+shift+j neighboring_window down
map alt+shift+right resize_window narrower
map alt+shift+left resize_window wider
map alt+shift+up resize_window taller
map alt+shift+down resize_window shorter
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
