[SddmTheme]
Name=ii-pixel
Description=Digz sddm
Type=sddm-theme
Author=iNiR bullshit copied
Version=1.0
Website=https://github.com/snowarch/iNiR
Screenshot=
MainScript=Main.qml
ConfigFile=theme.conf

[General]
background=assets/background.png
defaultBackground=assets/background.png
blurRadius=50

# iNiR Material You colors — updated automatically by sync-pixel-sddm.py on wallpaper change
primaryColor=#BFC8CB
onPrimaryColor=#394244
surfaceColor=#0E0E0E
surfaceContainerColor=#181A1A
onSurfaceColor=#E5E5E6
onSurfaceVariantColor=#AAABAC
backgroundColor=#0E0E0E
errorColor=#EE7D77
materialShapeChars=true
